observer重构
xiaojiaoyu100/aliyun-acm pull request #7
Opened 2019-11-22 10:01 UTC by linyihai

2019-11-22 17:14 UTC, zenghur requested changes
需要golint、goimports、go vet

2019-11-22 17:14 UTC, zenghur commented on diamond.go
> +	if u.Group == unit.Group && u.DataID == unit.DataID {
判断简化return u.Group == unit.Group && u.DataID == unit.DataID

2019-11-22 17:14 UTC, zenghur commented on observer.go
> +}
这里的代码似乎没有被调用，去掉把。正常一般用bytes.Compare

2019-11-22 17:14 UTC, zenghur commented on observer.go
> +	}
嵌套有点多，减少嵌套

2019-11-22 17:14 UTC, zenghur commented on observer.go
> +	Conf Conf
这里可能直接用Config就可以了，没有必要一个新的struct

2019-11-25 03:16 UTC, linyihai commented on observer.go
> +	Conf Conf
还需要附加Info{Group，DataID}, 才能知道Config属于哪个配置的。

2019-11-25 06:50 UTC, merged